CREATE FUNCTION CalculatePetAge(@petID UNIQUEIDENTIFIER)
RETURNS INT
AS
BEGIN
	DECLARE @YOB INT;
	DECLARE @CurrYear INT;

	SET @CurrYear= YEAR(GETDATE());

	SELECT @YOB = YearOfBirth
	FROM Pets
	WHERE PK_petID=@petID;
	RETURN(@CURRYEAR - @YOB);
END;