name: Apply Migration Scripts to Prod DB

on:
  push:
    branches:
      - production

jobs:
  migrate-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Intsall Flyway
      run: sudo snap install flyway --classic

    - name: Navigate to flyway folder
      run: cd ./flyway

    - name: Test direc
      run: ls

    - name: Add secret to flyway conf
      run: echo "\nflyway.password=12345678" >> flyway.conf

    - name: Run database migration
      run: flyway migrate

      
